### PR TITLE
Mention friboo-ext-zalando in README

### PR DESCRIPTION
**Pull request by dryewo**
Essentials is no longer directly based on friboo.

### CODE REVIEW

**Comment by lasomethingsomething** [comment]
@dryewo This seems like a super-simple PR to merge ... I'm going to give it a Zappr, we need one more (from you?) to close.

**Comment by lasomethingsomething** [comment]
👍

**Comment by dryewo** [comment]
👍

**Comment by dryewo** [comment]
@LappleApple I approved, but I'm not a maintainer, I have no "Merge" button.

**Pull request merged**
